# 예외 처리 

## 동기식 코드의 에러처리 
try...catch...finally 구문을 사용하면 에러가 나더라도 코드의 실행을 지속할 수 있습니다.


```js
try {
  console.log('에러가 나기 직전까지의 코드는 잘 실행됩니다.');
  new Array(-1); // RangeError: Invalid array length
  console.log('에러가 난 이후의 코드는 실행되지 않습니다.');
  // try block안에서 에러가 나면, 다음 코드를 실행하지 않고, catch로 코드의 실행을 이동시킨다. 
} catch (e) {
  if(e.name === 'RangeError'){
    alert('배열 생성자에 잘못된 인수가 입력되었습니다.')
  } else if(e.name === 'ReferenceError') {
    alert('선언되지 않은 변수가 사용되고 있습니다')
  }
  // 에러객체를 위와 같은 식으로 할 수 있다. 
  console.log('코드의 실행 흐름이 catch 블록으로 옮겨집니다.');
  alert(`다음과 같은 에러가 발생했습니다: ${e.name}: ${e.message}`);
  // 에러의 정보를 담고 잇는 객체가 생성되어서 catch 블록에 매개변수로 e가 들어온다.
  // e.name / e.message
  // catch block안에서 어떤 에러인지 파악할 수 있다. 
}
```

try 블록은 예외 처리를 위해서만 쓰이는 것은 아닙니다. try 블록 바로 뒤에 finally 블록이 오면, finally 블록에 있는 코드는 try 블록 안에서의 에러 발생 여부와 관계 없이 무조건 실행됩니다. 심지어 try 블록 내에서 return, break, continue 등으로 인해 코드의 실행 흐름이 즉시 이동될 때에도 마찬가지입니다.

로딩인디케이터를 띄우고 , 에러가 나면, 로딩인디케이터를 꺼야하고, 에러가 나지 않아도 로딩인디케이터를 꺼야 한다. 
그럴 때 finally를 사용한다. 
```js
for (let i of [1, 2, 3]) {
  try {
    if (i === 3) {
      break;
    }
  } finally {
    console.log(`현재 i의 값: ${i}`);
  }
}
```
finally 블록은 catch 블록과도 같이 사용됩니다. 이 때 코드의 실행 순서를 정리해 보면 다음과 같습니다.
try - catch - finally 

에러가 안 났을 때: try - finally
에러가 났을 때: try - 에러 발생 - catch - finally

3 가지 방식으로 사용할 수 있다. 
1. try - catch 
2. try - finally 
3. try - catch - finally 

```js
const even = parseInt(prompt('짝수를 입력하세요'));
if (even % 2 !== 0) {
  throw new Error('짝수가 아닙니다.');
  // error 생성자로부터 객체를 생성한다
  // 던질 수 있는 값에는 제한이 없다. 하지만, 에러 객체를 던져야만 제대로 동작한다. 반드시 에러객체를 던져야 한다. 
  // 자바스크립트 안에 내장되어 있는 객체이다 Error 객체 
}
```

```js
try{
  const even = parseInt(prompt('짝수를 입력하세요'));
  if (even % 2 !== 0) {
  throw new Error('짝수가 아닙니다.');
  }
} catch(err) {
  alert(err.message);
}
```
Error생성자는 메시지를 받는 기능밖에 없다. 
짝수 Error라는 생성자가 있어서, 에러객체를 만들 때 추가적인 정보, 왜 에러가 났는지에 대한 자세한 정보를 추가해서 만들면 좋겠다.

내 에러로 받고 싶은 걸 밸류로 받은 다음에
나머지놈들은  super로 에러 클래스의 생성자도 호출해준다. 
자체 에러 생성자를 만들어서 
```js
try{
  const even = parseInt(prompt('짝수를 입력하세요'));
  if (even < 2 ) {
    throw new NotPositiveError('짝수가 아닙니다.', even)
  } else if (even % 2 !== 0) {
    throw new EvenError('짝수를 입력하셔야 합니다.', even)
  }
  catch (e) {
    if(e instanceof NotPositiveError) {
      alert(e.message)
    } else if (e instanceof EvenError) {
      alert(e.message)
    }
  }
}
// 이런식으로 처리해 주고 싶다. (위 코드는 동작하지 않는 코드이다.)
```
```js
class MyError extends Error {
  constructor(value, ...params) {
    super(...params);
    this.value = value;
    this.name = 'MyError';
  }
}

try {
  const even = parseInt(prompt('짝수를 입력하세요'));
  if (even % 2 !== 0) {
    throw new MyError(even, '짝수가 아닙니다.');
  }
} catch (e) {
  if (e instanceof MyError) {
    console.log(e.value);
  }
}
```



## 비동기식 코드의 에러처리 

+ 에러에도 동기식 에러와 비동기식 에러가 있다.
+ 다르게 처리해줘야 한다. 

비동기식으로 작동하는 콜백의 내부에서 발생한 에러는, 콜백 바깥에 있는 try 블록으로는 잡아낼 수 없습니다.

비동기 코드 안에있는 에러는 잡히지가 않는다 (uncaught error )

JavaScript 엔진은 에러가 발생하는 순간 호출 스택을 되감는 과정을 거칩니다. 이 과정 중에 try 블록을 만나야 코드의 실행 흐름을 원상복구시킬 수 있습니다.

```js
function add(x, y) {
  // try{
  new Array(-1) // 
  return x + y;

  // } catch (e) {
  //   alert('잡았다')
  // }
}
// try 는 add2
function add2(x) {
  try{

  return add(x, 2); // `add`를 호출
  } catch (e) {
    alert('잡았다')
  }
}

function add2AndPrint(x) {
  const result = add2(x); // `add2`를 호출
  console.log(result); // `console.log`를 호출
}

add2AndPrint(3); // `add2AndPrint`를 호출
```
에러가 발생하면 자바스크립트엔진이 호출스택이 하나씩 지워가면서 트라이블록이 있는지 살펴본다. 
트라이블록이 있는지 되감아 보면서 확인한다. 

```js
function add(x, y) {
  new Array(-1) // 
  return x + y;
}
function add2(x) {
  return add(x, 2); // `add`를 호출
}
function add2AndPrint(x) {
  try{
  const result = add2(x); // `add2`를 호출
  console.log(result); // `console.log`를 호출
  } catch (e) {
    alert("catch!")
  }
}
add2AndPrint(3); // `add2AndPrint`를 호출
```
호출 정보를 스택에 쌓아놈 맨위에서 중간에 에러
나를 호출해주는 놈이 트라이블록 안에 들어있는지, 첫 번 째로 만나는 트라이 블록에서 에러가 잡힌다.
에러는 **호출 스택**과 관계가 있다. 

```js
function add(x, y) {
  new Array(-1) // 
  return x + y;
}
function add2(x) {
  try {
  return add(x, 2); // `add`를 호출
  } catch (e) {
    alert('add2에서 잡히나?') // 여기서 잡히게 된다. 
  }
}
function add2AndPrint(x) {
  try{
  const result = add2(x); // `add2`를 호출
  console.log(result); // `console.log`를 호출
  } catch (e) {
    alert("잡았다!")
  }
}
add2AndPrint(3); // `add2AndPrint`를 호출
```
```js
function add(x, y) {
  setTimeout(() => {
  new Array(-1) // 
  }, 0) 
  // 일단 작업큐에 들어갔다가 호출 스택이 비워지면 코드가 실행된다. 
  // 작업큐에 들어가 있는 동안 호출 스택이 비워진다. 트라이를 할 기회가 없어진다.

  return x + y;
}
function add2(x) {
  try {
  return add(x, 2); // `add`를 호출
  } catch (e) {
    alert('add2에서 잡히나?')
  }
}
function add2AndPrint(x) {
  try{
  const result = add2(x); // `add2`를 호출
  console.log(result); // `console.log`를 호출
  } catch (e) {
    alert("잡았다!")
  }
}
add2AndPrint(3); // `add2AndPrint`를 호출
```
[이벤트 리스너 트라이블록 예제](https://codepen.io/dbeat999/pen/bKqdwW)
- 트라이블록은 호출스택이 비워지면 아무런 효력이 없다. 
- 코드의 실행이 끝난뒤 이벤트 리스너가 실행되면 에러를 잡을 수 없다. 
- 실행되는 시점이 다르기 때문에 같은 호출 스택안에서 실행이 되는 경우에만 트라이 블록이 효력이 있다.
- 비동기로 실행되진 않지만, 나중에 실행되는 코드이다. 


비동기 함수 안에서의 트라이 캐치와 비동기 함수 밖에서의 트라이 캐치는 동작방식이 완전히 다르다. 
내부에서의 트라이캐치는 써져 있는대로 동작한다. 
하나의 호출 스택에 아니라, 여러 호출스택에 걸쳐서 에러를 잡을 수 있다. 

### promise 

- **Promise 객체는 세 가지 상태를 가질 수 있습니다**
  - pending - Promise 객체에 결과값이 채워지지 않은 상태
  - fulfilled - Promise 객체에 결과값이 채워진 상태
  - **rejected** - Promise 객체에 결과값을 채우려고 시도하다가 에러가 난 상태

```js
const p = new Promise(resolve => {
  const even = parseInt(prompt('짝수를 입력하세요'));
  if (even % 2 !== 0) {
    throw new Error('짝수가 아닙니다.');
  } else {
    resolve(even);
  }
});
// resolve함수를 호출하면, promiser가 채워줌 
// then 콜백안에서 반환한 값이 다음 프로미스에 들어간다. 

p.then(even => {
  return '짝수입니다.';
}, e => {
  return e.message;
}).then(msg => {
  alert(msg)
  });
// then(alert)
```
promise가 rejected 상태에 빠졌을 때 (값을 채워넣는 실패) 콜백을 두 가지 방법으로 등록해줄 수 있다. 
1. then 메소드 2번째 인수
2. catch 메소드 

비동기 프로그래밍이라는 작업 자체가 복잡하고, 자바스크립트 문법을 바꾸지 않으면서 기능을 추가하려다 보니까 어려워짐. 그래서 비동기 함수를 만듦
async await 

- 비동기 함수 안에서의 try catch 잡을 수 있다. 

```js
async function func() {
  try {
    const res = await fetch('https://nonexistent-domain.nowhere');
  } catch (e) {
    console.log(e.message);
  }
}

func(); // 출력 결과: Failed to fetch
// 호출스택과는 상관이 없다.
// 복잡하게 동작하지만, 다만 쓸 때는 동기식 코드처럼 쓸 수 있다. 
// 비동기 코드이지만(내부 동작방식은 복잡), 동기식 코드처럼 작성할 수 있다. 
```


**단, Promise 객체에 대해 await 구문을 사용하지 않는 경우, 에러가 발생해도 catch 블록으로 코드의 실행 흐름이 이동하지 않는다는 사실을 기억하세요.**

```js
async function func() {
  try {
    fetch('https://nonexistent-domain.nowhere');
  } catch (e) {
    console.log(e.message);
  }
}

func(); // 아무것도 출력되지 않습니다.
```
**동작방식을 이해하고 있어야 실수를 하지 않을 수 있다**

# 모듈

어떤 파일을 가지고 모듈이라고 함.

모듈이라는 시스템을 작성을 하고 실행시킬 때는 변환과정을 거친뒤에 실행시킨다. 

- webpack(자바스크립트로 의존성 분석) / parcel(html 태그로도 의존성을 분석) 
  - 모듈 번들러들은 여러 모듈을 하나의 파일로 합쳐주는 기능이다. 합칠 때, 그냥 합치는 것이 아니고 모듈이 아니라 일반적인 자바스크립트 동작할 수 있는 형태로 합쳐준다.
  - 그 과정안에서 최신 문법의 자바스크립트를 구형 문법으로 바꿔줘야 한다.
  - 모듈을 합쳐주는 기능 + 트랜스파일링(최신문법을 옛날 문법으로)

- ES2015 모듈은 기본적으로 JavaScript 코드를 담고 있는 파일입니다. 다만 일반적인 JavaScript 파일과는 다른 여러가지 차이점을 갖고 있습니다.
  - import 혹은 export 구문을 사용할 수 있습니다.
  - 별다른 처리를 해주지 않아도 엄격 모드(strict mode)로 동작합니다.
  - 모듈의 가장 바깥쪽에서 선언된 이름은 전역 스코프가 아니라 모듈 스코프에서 선언됩니다.

## 모듈 스코프

```js
// variables.js

var foo = 'bar'; 

// 이 파일이 모듈로서(모듈 안에서 사용되고 있다면) 사용되고 있다면, `undefined`가 출력됩니다.
console.log(window.foo);
```
- 모듈 스코프는 모듈 마다 개별적으로 존재한다.
- 다른 모듈이라면, 똑같은 변수 이름을 사용할 수 있다.
- 그러나, 모듈안에서 선언된 변수는 다른 모듈에서 사용할 수 있다. (export)

## export & import 

export를 해야 import를 할 수 있다. 
값을 가져오는 것이 아니라, 이름을 가져온다. (const let 이런 것들도 함께 가져오는 것)

## 선언과 동시에 export

## default export 

- export default 구문을 통해, 모듈을 대표하는 하나의 **값**을 지정하고 그 값을 다른 모듈에서 편하게 불러와서 사용할 수 있습니다. 이렇게 사용하는 값을 default export라고 부릅니다.
- export default 뒤에는 임의의 표현식(__값__)이 올 수 있습니다. 즉, 함수 표현식이나 클래스 표현식도 올 수 있습니다.

- default export는 이름이 없음(하나의 값만 있기 때문에, 모듈 당 하나의 export만 허용하기   때문에)
- inport할 때 원하는 이름으로 아무거나로 지정할 수 있다. 
- 모듈에는 하나의 default export 여러개의 named export를 할 수 있다. 

- 한꺼번 import 할 수 있다. 
  `import React, { Component, Fragment } from 'react';` 

```js
const foo = 'bar';

export { foo as FOO }; // FOO 라는 이름으로 export 됩니다. 대문자 FOO로 불러와야 한다.
```

`import { FOO as foo } from 'react'; // Comp라는 이름으로 import 됩니다.`

## 모듈 사용시 주의할 점  

- 모듈을 import를 한다는 것은 모듈 번들러는 임폴트를 하지 않으면 자바스크립트 코드를 실행시키지 않는다. 
- create react module bundler는 파일들을 모두 불러와서 이 파일들(모듈)에서 필요로 하는 모듈을 불러온다.
- 필요한 모듈만 번들링함(실행시킴) 
- import는 코드를 실행시키라는 명령이 아니다.
- 이 모듈이 로그 모듈을 필요로 한다는 것이다. 
- 모듈 번들러는 모듈안에 들어있는 코드를 한 번만 실행시킨다. 여러번 임폴트 한다고 해서 코드가 여러 번 실행된다는 의미는 아니다. 

- 같은 모듈을 여러 다른 모듈에서 불러와도, 모듈 내부의 코드는 단 한 번만 실행됩니다.
- import 구문과 export 구문은 모듈의 가장 바깥쪽 스코프에서만 사용할 수 있습니다.
- ECMAScript 공식 명세에는 모듈을 불러오는 방법에 대한 내용이 포함되어있지 않고, 이와 관련된 내용을 전적으로 모듈 구현체에 맡겼습니다. 따라서, 모듈을 어떤 환경에서 실행하느냐에 따라서 구체적인 로딩 순서나 동작방식이 조금씩 달라질 수 있습니다.(번들러에 따라서 모듈의 동작방식이 다를 수 있다.)



